### PR TITLE
Update arc_mapping.py to have name spaces more directly corresponding to ISA specs

### PR DESCRIPTION
**Pull request by pzentis**
Changed the name of an assay namespace to comply with the ISA subsection name, i.e."ARC:ISA:ASSAY:ASSAY METADATA" to "ARC:ISA:ASSAY:ASSAY" and "ARC:ISA:STUDY:STUDY METADATA" to "ARC:ISA:STUDY:STUDY".

### CODE REVIEW

**Comment by cmohl2013** [comment]
test currently fails, due to outdated configuration in the CI pipeline. Shortly to be fixed: #6 

Once this is fixed, can you rebase and push again?

**Comment by cmohl2013** [comment]
Namespaces have also to be modified in Tests accordingly:

https://github.com/cmohl2013/omero-arc/blob/f6c41105c8747fe09830df9aa4c0ff7e1cd9c3ca/test/abstract_arc_test.py#L150

**Comment by pzentis** [comment]
Just rebased and pushed again. Let me know if i did something wrong :)

**Comment by cmohl2013** [comment]
@pzentis 
Great, this worked.

Now: The Omero test project definition has to be modified: The namespaces of the anntoation objects have to be set to the new values.

https://github.com/cmohl2013/omero-arc/blob/f6c41105c8747fe09830df9aa4c0ff7e1cd9c3ca/test/abstract_arc_test.py#L150

**Comment by cmohl2013** [comment]
great, thank you, happy holiday

**Pull request merged**
